name: Build

on: [push]

jobs:
  build:
    name: Build the GitHub Pages
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - name: Install the dependencies
        run: docker-compose run --rm --user root -T npm install

      - name: Build the project
        run: docker-compose run --rm --user root -T npm run build

      - name: Setup the Git user name
        run: git config user.name "Amin NAIRI"

      - name: Setup the Git user email
        run: git config user.email "aminnairi@noreply.users.github.com"

      - name: Stage the changes
        run: git add --force docs

      - name: Commit the changes
        run: 'git commit --message ":package: production build" || true'

      - name: Push the changes
        run: git push