name: Code Style

on: [push, pull_request]

jobs:
  codestyle:
    name: Ensure that the code style remains consistent
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - name: Install the dependencies
        run: docker-compose run --rm --user root -T npm install

      - name: Lint the project
        run: docker-compose run --rm --user root -T npm run lint