name: Unit Tests

on: [push, pull_request]

jobs:
  unittests:
    name: Ensure that the unit tests are passing
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - name: Install the dependencies
        run: docker-compose run --rm --user root -T npm install

      - name: Run the unit tests
        run: docker-compose run --rm --user root -T npm test